Add new package "qtcreatorcdbext" for Qt Creator's CDB Extension
AdmiringWorm/chocolatey-packages pull request #274
Opened 2020-10-07 12:42 UTC by michaelweghorn

This adds the CDB debugger extension for Qt Creator. As discussed in #216, a new package is created rather than addint it into the existing `qtcreator` package.

The packaging files were created based on the ones for the 'qtcreator' package, i.e. those for the existing 'qtcreator' package  were initially copied, then adapted for this new package as needed.

Fixes: #216

Note: I've created this for Qt Creator 4.13.2 already, which is currently only available on the `master` branch, not `develop` yet, so this should probably not be integrated into the `develop` branch before PR #273.

2020-10-07 14:16 UTC, AdmiringWorm requested changes
In general the changes look good, but there are some things I need you to change before I can merge this package in.

Also, please rename the directory from `qtcreatorcdbext` to `qtcreator-cdbext` (this will be the id of the package).

2020-10-07 14:16 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/Readme.md
> +# [<img src="https://cdn.jsdelivr.net/gh/AdmiringWorm/chocolatey-packages@35eb3e49edb3411d779f64e57ef023abac8a3a06/icons/qtcreator.png" height="48" width="48" /> ![Qt Creator CDB Extension](https://i
It looks like you are using targeting the the qtcreator package for this badge.

Please change `qtcreator.svg` to `qtcreator-cdbext.svg`

2020-10-07 14:16 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/Readme.md
> +Qt Creator CDB Extension adds support for the Microsoft Console Debugger (CDB) to Qt Creator, a cross-platform, complete integrated development environment (IDE) for application developers to create
I think perhaps we may need a note here in the description, from what I gather there is a need for Visual Studio 2012+ due to a need to have `cdb.exe` available.

2020-10-07 14:16 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <version>4.13.2</version>
please set the version to `0.0`.
Having it to `4.13.2` will prevent the package to be updated and pushed (since that is the latest version).

2020-10-07 14:16 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <owners>AdmiringWorm</owners>
Please add a comma `,` and your username (or name if you prefer) to this section.
Since you are the one contributing the initial package.

2020-10-07 14:16 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <projectSourceUrl>http://code.qt.io/cgit/qt-creator/qt-creator.git/</projectSourceUrl>
Please update this link to

```suggestion
    <projectSourceUrl>https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/src/libs/qtcreatorcdbext/</projectSourceUrl>
```

^^ Is the actual source location of the extension.

2020-10-07 14:16 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <docsUrl>https://doc.qt.io/qtcreator/</docsUrl>
This url should be

```suggestion
    <docsUrl>https://wiki.qt.io/Qt_Creator_Windows_Debugging</docsUrl>
```

Which is the only location I can find any documentation of the extension.

2020-10-07 14:16 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <tags>c++ qt ide qtcreator qtcreatorcdbext admin</tags>
The tags should include either `extension` or `plugin` (not completely sure which one fits the best).

And the `admin` tag should be removed

2020-10-07 14:16 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +      <dependency id="qtcreator" version="4.13.2" />
Please change this to:

```suggestion
      <dependency id="qtcreator" version="[4.13.2]" />
```

This will ensure that the cdb extension only accepts the exact version of qtcreator (which would be appropriate since they are updated/provided at the same time).

This is of course something that will need to be also be updated in the `update.ps1` script to replace the version during update.

See https://github.com/AdmiringWorm/chocolatey-packages/blob/develop/automatic/privazer/update.ps1#L8-L10 as an example for that.

2020-10-07 14:18 UTC, AdmiringWorm commented
> Note: I've created this for Qt Creator 4.13.2 already, which is currently only available on the master branch, not develop yet, so this should probably not be integrated into the develop branch before PR #273.

The changes from the master branch have been pulled in to the develop branch now.

2020-10-08 08:45 UTC, AdmiringWorm commented
@michaelweghorn are you in a position to make the changes I requested?

2020-10-08 16:30 UTC, michaelweghorn commented on automatic/qtcreatorcdbext/Readme.md
> +# [<img src="https://cdn.jsdelivr.net/gh/AdmiringWorm/chocolatey-packages@35eb3e49edb3411d779f64e57ef023abac8a3a06/icons/qtcreator.png" height="48" width="48" /> ![Qt Creator CDB Extension](https://i
Done

2020-10-08 16:31 UTC, michaelweghorn commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <version>4.13.2</version>
Done.

2020-10-08 16:31 UTC, michaelweghorn commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <owners>AdmiringWorm</owners>
Done.

2020-10-08 16:32 UTC, michaelweghorn commented on automatic/qtcreatorcdbext/Readme.md
> +Qt Creator CDB Extension adds support for the Microsoft Console Debugger (CDB) to Qt Creator, a cross-platform, complete integrated development environment (IDE) for application developers to create
As far as I understand, you don't necessarily need Visual Studio, but the Windows Debugging Tools. I've added a link to https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/ which describes how to install them. I haven't added an explicit dependency to any Chocolatey package providing them, since there are multiple ways to install them and different packages that should do it.

2020-10-08 16:33 UTC, michaelweghorn commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <projectSourceUrl>http://code.qt.io/cgit/qt-creator/qt-creator.git/</projectSourceUrl>
Done.

2020-10-08 16:33 UTC, michaelweghorn commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <docsUrl>https://doc.qt.io/qtcreator/</docsUrl>
Done.

2020-10-08 16:33 UTC, michaelweghorn commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +      <dependency id="qtcreator" version="4.13.2" />
Done, thanks for the link to the example, that was very helpful!

2020-10-08 16:34 UTC, michaelweghorn commented
> In general the changes look good, but there are some things I need you to change before I can merge this package in.
> 
> Also, please rename the directory from `qtcreatorcdbext` to `qtcreator-cdbext` (this will be the id of the package).

Thanks for the super-quick review. I have changed the ID and renamed the directory accordingly and tried to address all your comments in the new version.

> The changes from the master branch have been pulled in to the develop branch now.
Thanks, I've rebased this PR on top of current develop branch.

2020-10-08 16:35 UTC, michaelweghorn commented on automatic/qtcreatorcdbext/qtcreatorcdbext.nuspec
> +    <tags>c++ qt ide qtcreator qtcreatorcdbext admin</tags>
I've added "plugin" now and removed the "admin" tag.

2020-10-08 17:23 UTC, AdmiringWorm commented on automatic/qtcreatorcdbext/Readme.md
> +Qt Creator CDB Extension adds support for the Microsoft Console Debugger (CDB) to Qt Creator, a cross-platform, complete integrated development environment (IDE) for application developers to create
I was under impression that it was part of Visual Studio installation, as mentioned here: https://wiki.qt.io/Qt_Creator_Windows_Debugging .

But the change you made looks good, and I don't really have that much experience with qtcreator to say exactly what is necessary and not.

2020-10-08 17:25 UTC, AdmiringWorm commented on automatic/qtcreator-cdbext/qtcreator-cdbext.nuspec
> +    <description><![CDATA[Qt Creator CDB Extension adds support for the Microsoft Console Debugger (CDB) to Qt Creator, a cross-platform, complete integrated development environment (IDE) for applica
Just for future reference, you do not need to update the `<description>` element.
Only the readme.md is necessary to be updated, which will be imported to the description when the package gets updated.

No harm in updating though, just wanted to mention it :smiley:

2020-10-08 17:26 UTC, AdmiringWorm approved these changes
Changes LGTM :+1:

Just need to set up a VM to test the package before I can merge this in.
Should be able to do that either tomorrow or during the weekend.

2020-10-08 17:27 UTC, merged

2020-10-08 17:29 UTC, AdmiringWorm commented
:facepalm: I forgot I had mergify set up.
Oh well.

The package won't be pushed until I merge it into the master branch, which I will do as soon as I have tested the package in the chocolatey VM.

2020-10-08 17:33 UTC, AdmiringWorm commented
@michaelweghorn your changes have been merged, thanks for your contribution 👍

If you have a chocolatey user account, please let me know which user it is so I can get you added as a co-maintainer of the package when I have pushed the package.

2020-10-09 06:11 UTC, michaelweghorn commented on automatic/qtcreator-cdbext/qtcreator-cdbext.nuspec
> +    <description><![CDATA[Qt Creator CDB Extension adds support for the Microsoft Console Debugger (CDB) to Qt Creator, a cross-platform, complete integrated development environment (IDE) for applica
Thanks for the hint. I had actually only manually updated `Readme.md` and the change showed up here as well (without me having thought of it at all) when I tested the update mechanism, so I committed it. :-)

2020-10-09 06:32 UTC, michaelweghorn commented
> @michaelweghorn your changes have been merged, thanks for your contribution +1

Thanks for your help and for merging!

> If you have a chocolatey user account, please let me know which user it is so I can get you added as a co-maintainer of the package when I have pushed the package.

I have just created an account with the username "michaelweghorn": https://chocolatey.org/profiles/michaelweghorn

2020-10-09 15:38 UTC, AdmiringWorm commented
Package have been pushed, and I have added you as a co-maintainer.
You should have received an email from chocolatey with a link to confirm being added.

2020-10-09 18:11 UTC, michaelweghorn commented
Thanks a lot, also for the follow-up improvements you did for the package!

2020-10-12 22:38 UTC, AdmiringWorm commented
@all-contributors add @michaelweghorn for code