(Tablacus) close before attempting to upgrade/uninstall
AdmiringWorm/chocolatey-packages pull request #294
Opened 2021-01-14 21:03 UTC by TheCakeIsNaOH

Closes `te64.exe` and `te32.exe` before upgrade/uninstall.

2021-01-14 22:42 UTC, TheCakeIsNaOH commented
It looks like the appveyor build failed due to an unrelated reason.

2021-01-18 22:17 UTC, AdmiringWorm requested changes

2021-01-18 22:17 UTC, AdmiringWorm commented on automatic/tablacus/tablacus.nuspec
> +      <dependency id="chocolatey-core.extension" version="1.3.4" />
Why have you added this dependency?
From what I can tell, there are no changes in this PR that requires the extension.

Please remove the dependency.

2021-01-18 22:17 UTC, AdmiringWorm commented on automatic/tablacus/tools/chocolateyBeforeModify.ps1
> +﻿$ErrorActionPreference = 'Stop'
TBH, this line is useless in the `chocolateyBeforeModify.ps1` file.
Even if the script fails, it won't abort the upgrade process.

Not saying you need to change it, just a note.

2021-01-18 22:32 UTC, TheCakeIsNaOH commented on automatic/tablacus/tablacus.nuspec
> +      <dependency id="chocolatey-core.extension" version="1.3.4" />
I thought that `Remove-Process` was in the `chocolatey-core.extension`? So  `chocolatey-core.extension` is not installed, it will fail to try to find `Remove-Process`

2021-01-18 22:36 UTC, TheCakeIsNaOH commented on automatic/tablacus/tools/chocolateyBeforeModify.ps1
> +﻿$ErrorActionPreference = 'Stop'
Yep, I just default to including it, even if it is not required. Just part of my linting pretty much.

2021-01-18 23:23 UTC, AdmiringWorm commented on automatic/tablacus/tablacus.nuspec
> +      <dependency id="chocolatey-core.extension" version="1.3.4" />
You are completely right, I was not aware that `Remove-Process` had been added to `chocolatey-core.extension`.
I assumed it was an alias of `Stop-Process` which is in powershell itself.

2021-01-18 23:23 UTC, AdmiringWorm approved these changes
LGTM

2021-01-18 23:24 UTC, merged

2021-01-18 23:25 UTC, AdmiringWorm commented
@TheCakeIsNaOH your changes have been merged, thanks for your contribution 👍

I won't be publishing a fix version with these changes, as tablacus is updated quite often.