Meld: Create shim to start meld from console (#282)
AdmiringWorm/chocolatey-packages pull request #299
Opened 2021-01-26 14:24 UTC by cmorty

Fixes #282

I'm far from familiar with Powershell, so comments are welcome. Also if there is a better way of getting the meld-path from the msi-installation.

2021-01-26 14:47 UTC, cmorty commented
@AdmiringWorm : It seems like there was some connection-issue while running AppVeyor. Could you restart the Check?

2021-02-13 04:28 UTC, AdmiringWorm requested changes

2021-02-13 04:28 UTC, AdmiringWorm commented on automatic/meld/tools/chocolateyInstall.ps1
> +$installlogfile="$($env:TEMP)\$($env:chocolateyPackageName).$($env:chocolateyPackageVersion).MsiInstall.log"
We can not guarantee that there will be a install log file. A user can override the installation arguments, and thus not pass in a log file, or a different path.

A better way would be to search for in the registry for the installation directory, see the helper [Get-UninstallRegistlyKey](https://docs.chocolatey.org/en-us/create/functions/get-uninstallregistrykey).

2021-02-13 04:28 UTC, AdmiringWorm commented on automatic/meld/update.ps1
> +[CmdletBinding()]
If this change is to remove the UTF8 BOM encoding, please revert that change.
Removing BOM on powershell files can have unintended consequences, especially if there is a change in the future that introduces non-ansi characters (only relevant for Windows PowerShell, not PowerShell Core).

2021-02-13 04:28 UTC, AdmiringWorm commented on automatic/meld/update.ps1
> +Import-Module "$PSScriptRoot\..\..\scripts\au_extensions.psm1"
Just a note:
You don't really have to import this file, it is automatically imported during the full update process (useful for debugging a single file though).

2021-02-14 11:33 UTC, cmorty commented on automatic/meld/update.ps1
> +[CmdletBinding()]
Ooops. That was not by intent. VSCode seems to have "fixed" this.

2021-02-14 11:35 UTC, cmorty commented on automatic/meld/update.ps1
> +Import-Module "$PSScriptRoot\..\..\scripts\au_extensions.psm1"
I added it, because otherwise I always had to do the full update-process, which made testing more complicated than necessary (that's also why I put it into a separate commit.). Also there some other packages having this. Do you want me to remove it?

2021-02-14 11:43 UTC, AdmiringWorm commented on automatic/meld/update.ps1
> +Import-Module "$PSScriptRoot\..\..\scripts\au_extensions.psm1"
nah, you can keep it. I just added the comment as a note in case you didn't know it would work on the update server even when not included.

2021-02-15 08:13 UTC, cmorty commented on automatic/meld/tools/chocolateyInstall.ps1
> +$installlogfile="$($env:TEMP)\$($env:chocolateyPackageName).$($env:chocolateyPackageVersion).MsiInstall.log"
Ok, I looked into this. Get-UninstallRegistlyKey gives me:
```
AuthorizedCDFPrefix :
Comments            :
Contact             : meld-list@gnome.org
DisplayVersion      : 3.20.2
HelpLink            :
HelpTelephone       :
InstallDate         : 20210215
InstallLocation     :
InstallSource       : C:\ProgramData\chocolatey\lib\meld\tools\
ModifyPath          : MsiExec.exe /I{26F92930-794F-436D-8805-6CC38605144E}
Publisher           : The Meld project
Readme              : 
Size                :
EstimatedSize       : 113653
UninstallString     : MsiExec.exe /I{26F92930-794F-436D-8805-6CC38605144E}
URLInfoAbout        : http://meldmerge.org
URLUpdateInfo       :
VersionMajor        : 3
VersionMinor        : 20
WindowsInstaller    : 1
Version             : 51642370
Language            : 1033
DisplayName         : Meld
PSPath              : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{26F92930-794F-436D-8805-6CC38605144E}
PSParentPath        : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall
PSChildName         : {26F92930-794F-436D-8805-6CC38605144E}
PSProvider          : Microsoft.PowerShell.Core\Registry
```
Searching the registry for `26F92930-794F-436D-8805-6CC38605144E` did not provide any additional information. Thus I'm afraid I'll need another pointer.

Alternatively I'd adjust the script to make it more robust against the user modifyig `silentArgs` and print a warning if the log file does not exist.

2021-02-15 11:00 UTC, AdmiringWorm commented on automatic/meld/tools/chocolateyInstall.ps1
> +$installlogfile="$($env:TEMP)\$($env:chocolateyPackageName).$($env:chocolateyPackageVersion).MsiInstall.log"
That is unfortunate, I guess we need to rely on the log file then (we could use the `Get-AppLocation` helper in the [`chocolatey-core.extension`](https://chocolatey.org/packages/chocolatey-core.extension) package. Don't really want to do that due to a bug in the helper, which picks up shims though).

Anyways, a check if the log file exist need to be implemented before trying to read it, and just output a warning to the user if it doesn't exist.

2021-02-15 11:04 UTC, AdmiringWorm commented on automatic/meld/update.ps1
> +[CmdletBinding()]
that is odd, as I have added a configuration file to the repository that should override the defaults of vscode and save PowerShell with BOM enabled (*could be it only works on new files :confused:*).

Sounds more like you perhaps have an extension enabled that overrides that again.
Would like to know which, so at least I could add a configuration file to ensure it is saved with BOM (*if possible*)

2021-02-15 11:07 UTC, AdmiringWorm commented
btw, would be great if you could rebase against the latest `develop` branch, I pushed an update to it so packages no longer gets tested on the VS 2015 image (due to TLS issues).

2021-02-19 23:24 UTC, AdmiringWorm commented on automatic/meld/tools/chocolateyInstall.ps1
> +$installlogfile="$($env:TEMP)\$($env:chocolateyPackageName).$($env:chocolateyPackageVersion).MsiInstall.log"
I did some research, and it seems that meld is creating a registry key at `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Meld` (Wow6432Node is not used on 32bit Windows) and in that location, it has a registry sub key that includes the location that meld was installed to.

Is this something that you are able to update the installation script to?

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Meld]
"InstallDir"="C:\\Program Files (x86)\\Meld\\"
"Executable"="C:\\Program Files (x86)\\Meld\\Meld.exe"
```

2021-02-21 21:19 UTC, AdmiringWorm approved these changes
I made a change to the pull request to use the found registry entries instead.
This pull request will be merged once the unit tests succeed

2021-02-21 21:20 UTC, AdmiringWorm commented on automatic/meld/update.ps1
> +[CmdletBinding()]
I didn't bother to fix this at the time, maybe I will do so in the future.

2021-02-21 21:22 UTC, merged

2021-02-21 21:25 UTC, AdmiringWorm commented
@allcontributors please add @cmorty for ideas and code

2021-02-22 06:33 UTC, cmorty commented
@AdmiringWorm: I planned to look into this today, but I'ts not like I'm running out of stuff to do. So, thanks a lot for taking care of this!

2021-02-22 07:06 UTC, AdmiringWorm commented
No worries, I had already decided to work on the repository, so figured I take the pull request while I was at it.

I haven't yet pushed the changed to chocolatey yet though, but I expect to do that within the next few days (I am hoping a new version of meld comes out instead though).

2021-02-23 01:29 UTC, AdmiringWorm commented
I found that meld 3.20.3 was failing the verifier, so a new version with these changes has been pushed to chocolatey.org