Update MailingListUrl to Ubisoft's Discord
AdmiringWorm/chocolatey-packages pull request #401
Opened 2023-07-08 14:55 UTC by Zoullx

Ubisoft's forums have been closed and Discord is now used in place of those forums. This just updates the MailingListUrl to the Discord because since the forum link was broken it was causing the package to fail testing.

2023-09-04 10:11 UTC, AdmiringWorm requested changes
Thank you for opening this PR, and I apologies for taking so long to be able to have a look at it. One thing before I can merge this.

2023-09-04 10:11 UTC, AdmiringWorm commented on automatic/ubisoft-connect/ubisoft-connect.nuspec
> +    <mailingListUrl>https://discord.gg/ubisoftofficial</mailingListUrl>
A discord channel would not be a mailing list or a forum. As such, I think it would be better to remove the mailing list url entirely instead.

2023-09-05 16:55 UTC, Zoullx commented on automatic/ubisoft-connect/ubisoft-connect.nuspec
> +    <mailingListUrl>https://discord.gg/ubisoftofficial</mailingListUrl>
That's just what Ubisoft had listed as their new "forum", so that's why I put it, but I'll remove it. Thanks for taking a look at this.

2023-09-05 19:00 UTC, Zoullx commented
Alright, MailingListUrl has been removed and committed, so this should take care of Ubisoft to auto update and pass validation testing again.

2023-09-25 16:09 UTC, AdmiringWorm approved these changes
LGTM

2023-09-25 16:22 UTC, merged

2023-09-25 16:23 UTC, AdmiringWorm commented
@Zoullx, your changes have been merged. Thanks for your contribution 👍

Apologies for taking so long to get this PR merged. I'll trigger a new version being pushed to the Community Repository immediately.

2023-09-25 16:30 UTC, Zoullx commented
Awesome, thank you so much for getting to it. I'm just glad to have the package fixed for auto updates

2023-10-02 18:05 UTC, AdmiringWorm commented
@all-contributors please add @Zoullx for docs